@startuml Flask 0.1

' https://www.planttext.com/

start

if (debug in options?) then (yes)
    :self.debug = options.pop('debug');
else (no)
    :pass;
endif

:options['use_reloader'] = self.debug;
:options['use_debugger'] = self.debug;
:run_simple(host, port, self, **options);

end

@enduml