# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
import sys
import os
import datetime
import warnings

warnings.simplefilter('ignore', DeprecationWarning)

import pkg_resources

# skip raw nodes
from sphinx.writers.text import TextTranslator
from sphinx.writers.latex import LaTeXTranslator

from docutils import nodes
from docutils import utils
from docutils.parsers.rst import Directive


def raw(*arg):
    raise nodes.SkipNode
TextTranslator.visit_raw = raw


# make sure :app:`Pyramid` doesn't mess up LaTeX rendering
def nothing(*arg):
    pass
LaTeXTranslator.visit_inline = nothing
LaTeXTranslator.depart_inline = nothing

book = os.environ.get('BOOK')

# -- Project information -----------------------------------------------------
thisyear = datetime.datetime.now().year
project = 'Learning Notes'
copyright = '2020-%s, Leon Lee' % thisyear
author = 'Leon Lee'

show_authors = True

# The full version, including alpha/beta/rc tags
version = "Alpha"
release = version


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    #'repoze.sphinx.autointerface',  # pip install repoze.sphinx.autointerface
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.viewcode',
    #'sphinxcontrib.autoprogram', # pip install sphinxcontrib-autoprogram
    'sphinx_copybutton',
    'sphinx.ext.autosummary',
    # enable pylons_sphinx_latesturl when this branch is no longer "latest"
    # 'pylons_sphinx_latesturl',
]

intersphinx_mapping = {
    # 'colander': ('https://docs.pylonsproject.org/projects/colander/en/latest/', None),
    # 'cookbook': ('https://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/', None),
    # 'deform': ('https://docs.pylonsproject.org/projects/deform/en/latest/', None),
    # 'jinja2': ('https://docs.pylonsproject.org/projects/pyramid-jinja2/en/latest/', None),
    # 'pylonswebframework': ('https://docs.pylonsproject.org/projects/pylons-webframework/en/latest/', None),
    # 'python': ('https://docs.python.org/3/', None),
    # 'pytest': ('https://docs.pytest.org/en/latest/', None),
    # 'sqla': ('https://docs.sqlalchemy.org/en/latest/', None),
    # 'tm': ('https://docs.pylonsproject.org/projects/pyramid-tm/en/latest/', None),
    # 'toolbar': ('https://docs.pylonsproject.org/projects/pyramid-debugtoolbar/en/latest/', None),
    # 'transaction': ('https://transaction.readthedocs.io/en/latest/', None),
    # 'tutorials': ('https://docs.pylonsproject.org/projects/pyramid-tutorials/en/latest/', None),
    # 'venusian': ('https://docs.pylonsproject.org/projects/venusian/en/latest/', None),
    # 'webtest': ('https://docs.pylonsproject.org/projects/webtest/en/latest/', None),
    # 'webob': ('https://docs.pylonsproject.org/projects/webob/en/latest/', None),
    # 'zcml': (
    # 'https://docs.pylonsproject.org/projects/pyramid-zcml/en/latest/', None),
}


# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
today_fmt = '%B %d, %Y'

exclude_patterns = [
    "./CodeReading/Flask/Flask-0.1/src",
    "./CodeReading/TinyDB/1.0.0/docs"
]

add_module_names = False

if book:
    pygments_style = 'bw'

# The suffix of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'pyramid'
html_theme = 'sphinx13'

html_theme_path = ['_themes']
html_css_files = [
    # 'basic.css',  # included through inheritance from the basic theme
    'sphinx13.css',
]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_sidebars = {'**': [
    'localtoc.html',
    #'ethicalads.html',
    'relations.html',
    'sourcelink.html',
    'searchbox.html',
]}

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = 'The Leon\'s Learning Notes Version %s' % release
html_title = 'The Leon\'s Learning Notes' 

#html_additional_pages = {'contents': 'contents.html'}

#html_use_opensearch = 'https://www.sphinx-doc.org/en/master'
#html_baseurl = 'https://www.sphinx-doc.org/en/master/'
#html_favicon = '_static/favicon.svg'

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = '%b %d, %Y'

# Do not use smart quotes.
smartquotes = False

# Output file base name for HTML help builder.
htmlhelp_basename = 'Learning-Notes'

# Options for LaTeX output
# ------------------------

latex_engine = 'xelatex'
latex_use_xindy = False

# The paper size ('letter' or 'a4').
latex_paper_size = 'letter'

# The font size ('10pt', '11pt' or '12pt').
latex_font_size = '10pt'

latex_additional_files = [
    '_static/latex-note.png',
    '_static/latex-warning.png',
]

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, document class [howto/manual]).
latex_documents = [
  ('latexindex', 'pyramid.tex',
   'The Pyramid Web Framework',
   'Chris McDonough', 'manual'),
    ]

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
latex_toplevel_sectioning = "section"

# If false, no module index is generated.
latex_domain_indices = False

## Say, for a moment that you have a twoside document that needs a 3cm
## inner margin to allow for binding and at least two centimetres the
## rest of the way around. You've been using the a4wide package up until
## now, because you like the amount of text it places on the
## page. Perhaps try something like this in your preamble:

## \usepackage[bindingoffset=1cm,textheight=22cm,hdivide={2cm,*,2cm},vdivide={*,22cm,*}]{geometry}

## _PREAMBLE = r"""\usepackage[bindingoffset=0.45in,textheight=7.25in,hdivide={0.5in,*,0.75in},vdivide={1in,7.25in,1in},papersize={7.5in,9.25in}]{geometry}"""

_PREAMBLE = r"""
\usepackage[]{geometry}
\geometry{bindingoffset=0.45in,textheight=7.25in,hdivide={0.5in,*,0.75in},vdivide={1in,7.25in,1in},papersize={7.5in,9.25in}}
%XeLaTeX packages
\usepackage{xltxtra}
\usepackage{fontspec} %Font package
\usepackage{xunicode}
%Select fonts
\setmainfont[Mapping=tex-text]{nimbusserif}
\setsansfont[Mapping=tex-text]{nimbussans}
\setmonofont{nimbusmono}
\hypersetup{
    colorlinks=true,
    linkcolor=black,
    citecolor=black,
    filecolor=black,
    urlcolor=black
}
\fvset{frame=single,xleftmargin=9pt,numbersep=4pt}
\pagestyle{fancy}
% header and footer styles
\renewcommand{\chaptermark}[1]%
  {\markboth{\MakeUppercase{\thechapter.\ #1}}{}
  }
\renewcommand{\sectionmark}[1]%
  {\markright{\MakeUppercase{\thesection.\ #1}}
  }
% defaults for fancy style
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}
\fancyhf{}
\fancyfoot[C]{\thepage}
% plain style
\fancypagestyle{plain}{
  \renewcommand{\headrulewidth}{0pt} % ho header line
  \renewcommand{\footrulewidth}{0pt}% no footer line
  \fancyhf{} % empty header and footer
  \fancyfoot[C]{\thepage}
}
% title page styles
\makeatletter
\def\@subtitle{\relax}
\newcommand{\subtitle}[1]{\gdef\@subtitle{#1}}
\renewcommand{\maketitle}{
  \begin{titlepage}
    {\rm\Huge\@title\par}
    {\em\large\py@release\releaseinfo\par}
    \if\@subtitle\relax\else\large\@subtitle\par\fi
    {\large\@author\par}
  \end{titlepage}
}
\makeatother
% Redefine link and title colors
\definecolor{TitleColor}{rgb}{0,0,0}
\definecolor{InnerLinkColor}{rgb}{0.208,0.374,0.486}
\definecolor{OuterLinkColor}{rgb}{0.216,0.439,0.388}
% Redefine these colors to something not white if you want to have colored
% background and border for code examples.
\definecolor{VerbatimColor}{rgb}{1,1,1}
\definecolor{VerbatimBorderColor}{rgb}{1,1,1}
% icons in note and warning boxes
\usepackage{ifthen}
% Keep a copy of the original sphinxadmonition environment
\let\origbeginadmon\sphinxadmonition
\let\origendadmon\endsphinxadmonition
% Redefine the sphinxadmonition environment so we can add our own code to it
\renewenvironment{sphinxadmonition}[2]{%
  \origbeginadmon{#1}{}% equivalent to original \begin{sphinxadmonition}{#1}{#2}
  % load graphics
  \ifthenelse{\equal{#1}{warning}}{\includegraphics{latex-warning.png}}{}
  \ifthenelse{\equal{#1}{note}}{\includegraphics{latex-note.png}}{}
  % etc.
  }{%
\origendadmon % equivalent to original \end{sphinxadmonition}
}
% try to prevent code-block boxes from splitting across pages
\sloppy
\widowpenalty=300
\clubpenalty=300
\setlength{\parskip}{3ex plus 2ex minus 2ex}
% suppress page numbers on pages showing part title
\makeatletter
\let\sv@endpart\@endpart
\def\@endpart{\thispagestyle{empty}\sv@endpart}
\makeatother
% prevent page numbers in TOC (reset to fancy by frontmatter directive)
\pagestyle{empty}
"""

latex_elements = {
    'preamble': _PREAMBLE,
    'releasename': 'Version',
    'title': r'The Leon\'s Learning Notes',
#    'pointsize':'12pt', # uncomment for 12pt version
}

# secnumdepth counter reset to 2 causes numbering in related matter;
# reset to -1 causes chapters to not be numbered, reset to -2 causes
# parts to not be numbered.

#part	      -1
#chapter       0
#section       1
#subsection    2
#subsubsection 3
#paragraph     4
#subparagraph  5


class FrontMatter(Directive):
    def run(self):
        return [nodes.raw(
            '',
            format='latex')]


class MainMatter(Directive):
    def run(self):
        return [nodes.raw(
            '',
            format='latex')]


class BackMatter(Directive):
    def run(self):
        return [nodes.raw(
            '',
            format='latex')]


def app_role(role, rawtext, text, lineno, inliner, options={}, content=[]):
    """custom role for :app: marker, does nothing in particular except allow
    :app:`Pyramid` to work (for later search and replace)."""
    if 'class' in options:
        assert 'classes' not in options
        options['classes'] = options['class']
        del options['class']
    return [nodes.inline(rawtext, utils.unescape(text), **options)], []


def setup(app):
    app.add_role('app', app_role)
    app.add_directive('frontmatter', FrontMatter)
    app.add_directive('mainmatter', MainMatter)
    app.add_directive('backmatter', BackMatter)


# turn off all line numbers in latex formatting

## from pygments.formatters import LatexFormatter
## from sphinx.highlighting import PygmentsBridge

## class NoLinenosLatexFormatter(LatexFormatter):
##     def __init__(self, **options):
##         LatexFormatter.__init__(self, **options)
##         self.linenos = False

## PygmentsBridge.latex_formatter = NoLinenosLatexFormatter

# -- Options for Epub output ---------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = 'The Leon\'s Learning Notes, Version %s' % release
epub_author = 'Leon Lee'
epub_publisher = 'www.liangz.org'
epub_copyright = '2020-%d' % thisyear

# The language of the text. It defaults to the language option
# or en if the language is not set.
epub_language = 'zh-CN'

# The scheme of the identifier. Typical schemes are ISBN or URL.
epub_scheme = 'url'

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
epub_identifier = 'www.liangz.org'

# A unique identification for the text.
epub_uid = 'The Leon\'s Learning Notes, Version %s' % release

# A list of files that should not be packed into the epub file.
# pyramid
# epub_exclude_files = ['_static/opensearch.xml', '_static/doctools.js',
#     '_static/jquery.js', '_static/searchtools.js', '_static/underscore.js',
#     '_static/basic.css', 'search.html', '_static/websupport.js']

epub_exclude_files = ['_static/opensearch.xml', '_static/doctools.js',
                      '_static/jquery.js', '_static/searchtools.js',
                      '_static/sphinx_highlight.js',
                      '_static/underscore.js', '_static/basic.css',
                      '_static/language_data.js',
                      'search.html', '_static/websupport.js']

# The depth of the table of contents in toc.ncx.
epub_tocdepth = 3

epub_fix_images = False
epub_max_image_width = 0
epub_show_urls = 'inline'
epub_use_index = False
epub_description = 'The Leon\'s Learning Notes'

# For a list of all settings, visit http://sphinx-doc.org/config.html

# -- Options for linkcheck builder -------------------------------------------

# List of items to ignore when running linkcheck
linkcheck_ignore = [
    r'http://localhost:\d+',
    r'http://localhost',
    r'https://web.libera.chat/#pyramid',  # JavaScript "anchor"
]
